# fly.toml app configuration file generated for bank-app-bold-rain-3693 on 2025-08-21T10:57:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bank-app-bold-rain-3693'
primary_region = 'lhr'

[build]
  dockerfile = "server/Dockerfile"
  context = "."

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.healthz]
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    path = "/healthz"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
